sudo: required
dist: trusty
language: node_js
node_js:
  - "4.2"
  - "6"
addons:
  apt:
    packages:
    - graphicsmagick
before_script:
  - gm version
  - gm identify -format "Metadata: %q %Q %b %h %k %w" "tests/fixtures/a/jukka-paasonen.jpg"
after_success: "npm run coverage"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
