sudo: true
language: node_js
node_js:
  - "4.2"
  - "6"
before_script:
  - sudo apt-get install -y graphicsmagick
after_success: "npm run coverage"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
