sudo: required
dist: trusty
language: node_js
node_js:
  - "4.2"
  - "6"
addons:
  apt:
    packages:
    - graphicsmagick
before_script:
  - gm version
after_success: "npm run coverage"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
