# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4.2"

version: "{build}-{branch}"

init:
  - git config --global core.longpaths true
  - npm install --global node-gyp

clone_depth: 1

matrix:
  fast_finish: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile http://downloads.sourceforge.net/graphicsmagick/GraphicsMagick-1.3.24-Q16-win64-dll.exe
  - GraphicsMagick-1.3.24-Q16-win64-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - gm version
  - npm run lint
  - npm test

build: off
